### ISSUE TITLE
Permission problem with rostervm 

### ISSUE THREAD

**Issue by ruthger** [ArchipelProject/Archipel#1118]
I have a problem adding new hypervisors and virtualmachines to my roster. The problem started with upgrading ejabberd from 2.1.13 to 14.12. If I rollback the upgrade it will work again. I have used the new yml config from the wiki. I can add existing hypervisors and virtualmachines to my roster.

Steps I have tried to correct the problem:
- Setup a new ejabberd server on a test server following all steps in the wiki. The same error occurs.
- Reinstall Archipel-Agent from nightly
- Reinstall Archipel-Agent from git
- Reinstall Archipel-Client from nightly
- Checked permissions.sqlite in /var/log and /vm/driver/uuid. jid of admin exists in users and user_have_premissions (with all).
- Checked archipel-adminaccount list. jid of admin exists
- Checked archipel-ejabberdadmin list. jid of admin exists 

INFO    ::2015-03-05 11:42:12::utils.py:72::TNArchipelHypervisor.check_perm (xxx@yyy.zzz)::Checking permission for action rostervm asked by xxx@yyy.zzz
INFO    ::2015-03-05 11:42:12::utils.py:72::TNArchipelHypervisor.check_acp (xxx@yyy.zzz)::acp received: from: xxx@yyy.zzz, type: get, namespace: archipel:hypervisor:control, action: rostervm

Can you please give me a hint or if you want more info I will try to provide it.

**Comment by CyrilPeponnet** [comment]
What's the issue ?

**Comment by ruthger** [comment]
If I create a new hypervisor or virtualmachine and add it to my roster the contact is added but has no icon or dashboard. Only the chat is shown.
The client request permission for the rostervm many times until the browse freshes.
In the log the two INFO lines are written multiple times.

**Comment by CyrilPeponnet** [comment]
The new yaml configuration has not been fully tested with latest releases
of ejabberd. The behavior you have is basically because something get wrong
with vcards. You can try something:

Instead of

```yaml

mod_MODULE: []

```

Use


```yaml

mod_MODULE: {}

```

So the module section will become:

```yaml
    mod_adhoc: {}
    mod_announce:
        access: announce
    mod_caps: {}
    mod_configure: {}
    mod_disco: {}
    mod_http_bind:
        max_inactivity: 400 # timeout valie for BOSH usefull for a large
number of VM
    mod_irc: {}
    mod_last: {}
    mod_muc:
        access: muc
        access_create: muc_create
        access_persistent: muc_create
        access_admin: muc_admin
    mod_offline: {}
    mod_privacy: {}
    mod_private: {}
    mod_pubsub:
        access_createnode: pubsub_createnode
        ignore_pep_from_offline: true
        last_item_cache: false
        max_items_node: 1000
        plugins:
            - "flat"
            - "hometree"
            - "pep"
    mod_register:
        access: register
    mod_roster: {}
    mod_shared_roster: {}
mod_time: {}
mod_vcard: {}
mod_version: {}
mod_admin_extra: {}

```

**Comment by CyrilPeponnet** [comment]
The new yaml configuration has not been fully tested with latest releases
of ejabberd. The behavior you have is basically because something get wrong
with vcards. You can try something:

Instead of

```yaml
mod_MODULE: []
```

Use


```yaml

mod_MODULE: {}

```

So the module section will become:

```yaml
    mod_adhoc: {}
    mod_announce:
        access: announce
    mod_caps: {}
    mod_configure: {}
    mod_disco: {}
    mod_http_bind:
        max_inactivity: 400 # timeout valie for BOSH usefull for a large number of VM
    mod_irc: {}
    mod_last: {}
    mod_muc:
        access: muc
        access_create: muc_create
        access_persistent: muc_create
        access_admin: muc_admin
    mod_offline: {}
    mod_privacy: {}
    mod_private: {}
    mod_pubsub:
        access_createnode: pubsub_createnode
        ignore_pep_from_offline: true
        last_item_cache: false
        max_items_node: 1000
        plugins:
            - "flat"
            - "hometree"
            - "pep"
    mod_register:
        access: register
    mod_roster: {}
    mod_shared_roster: {}
mod_time: {}
mod_vcard: {}
mod_version: {}
mod_admin_extra: {}

```
