### ISSUE TITLE
Ejabberd

### ISSUE THREAD

**Issue by volga629** [ArchipelProject/Archipel#1153]
Hello Everyone,
Having some issue with ejabberd where can't  maintain xmpp users from web UI. This version 15.07 of ejabberd and here are relevant configuration.
Any help thank you.

Config

```
  - 
    port: 4560
    module: ejabberd_xmlrpc
    access_commands:
      xmlrpc_access:
        commands: all
        options: {}

  xmlrpc_access:
    admin: allow

```
Error

```
 @ejabberd_xmlrpc:build_fault_response:380 Error -118
 A problem '{error,account_unprivileged}' occurred executing the command srg_list with arguments

```

**Comment by CyrilPeponnet** [comment]
https://github.com/processone/ejabberd/issues/504

If you need to make them persistent you have to add them to the yamll.

**Comment by volga629** [comment]
Yes I have this in conf. And I can't edit or do any operation in web ui regard user creation or modification.

```
acl:
  ##
  ## The 'admin' ACL grants administrative privileges to XMPP accounts.
  ## You can put here as many accounts as you want.
  ##
  admin:
    user:
      - "admin": "ns508284.ip-167-114-64.net"

```
